# -*- coding: utf-8 -*-
"""
fe_llm/energy_lm/data/prepare_code.py —— 从 codeparrot-clean 构建字符级 Python 代码语料
=========================================================================================
为"从 0 自建 code 模型"准备训练语料。源数据 `codeparrot/codeparrot-clean`：
GitHub 公开仓库里清洗 + 去重过的**纯 Python** 代码（非门禁），按 file-*.json.gz 分片，
每条记录含 content / path / autogenerated / line_max / alpha_frac 等字段。

本脚本：
    1. 用 hf_hub_download 拉一个（或多个）分片到 HF 缓存（断点续传、可复用）。
    2. 逐条读取，按质量字段过滤（剔除自动生成 / minified 超长行 / 过短过长 / 低字母占比）。
    3. 文件间插入分隔，拼成一条连续字符流，达到 --target-mb 即停（一个分片解压 >500MB，
       通常一个分片就够 150MB 目标，不必全读）。
    4. 落盘到 data/code/python_corpus.txt，并打印字表规模 / 文件数 / 体积。

字符级建模理由：代码字符集小（ASCII 为主，词表才一两百），局部结构强，字级模型不需 BPE
也能学到代码模式，且与本项目的字符级 SeqEnergyNet 架构一致。

运行：
    python -m fe_llm.energy_lm.data.prepare_code --target-mb 150
    python -m fe_llm.energy_lm.data.prepare_code --target-mb 200 --max-shards 3
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

REPO = "codeparrot/codeparrot-clean"
OUT_DIR = os.path.join("data", "code")
DEFAULT_OUT = "python_corpus.txt"
FILE_SEP = "\n\n"   # 文件间分隔（字符级，模型隐式学到文件边界）


def iter_records(shard_path: str):
    """逐行读取 json.gz 分片中的记录（容错坏行）。"""
    with gzip.open(shard_path, "rt", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except ValueError:
                continue


def keep(rec: dict, min_chars: int, max_chars: int, max_line: int, min_alpha: float) -> bool:
    """质量过滤：剔除自动生成、minified、过短过长、低字母占比的文件。"""
    if rec.get("autogenerated"):
        return False
    content = rec.get("content") or ""
    n = len(content)
    if n < min_chars or n > max_chars:
        return False
    line_max = rec.get("line_max")
    if line_max is not None and line_max > max_line:
        return False   # 单行超长 = 压缩/生成代码，字符级学不到好结构
    alpha = rec.get("alpha_frac")
    if alpha is not None and alpha < min_alpha:
        return False
    return True


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:
        pass
    ap = argparse.ArgumentParser(description="从 codeparrot-clean 构建字符级 Python 代码语料。")
    ap.add_argument("--target-mb", type=float, default=150.0, help="目标语料体积（解压后 MB）")
    ap.add_argument("--max-shards", type=int, default=2, help="最多下载几个分片直到达标")
    ap.add_argument("--start-shard", type=int, default=1, help="起始分片编号（1..53）")
    ap.add_argument("--min-chars", type=int, default=200, help="单文件最少字符")
    ap.add_argument("--max-chars", type=int, default=40000, help="单文件最多字符（剔除超大文件）")
    ap.add_argument("--max-line", type=int, default=400, help="最长行上限（剔除 minified）")
    ap.add_argument("--min-alpha", type=float, default=0.25, help="字母占比下限")
    ap.add_argument("--out", default=DEFAULT_OUT, help="输出文件（相对 data/code 或绝对路径）")
    args = ap.parse_args()

    from huggingface_hub import hf_hub_download

    out_path = args.out if os.path.isabs(args.out) else os.path.join(OUT_DIR, args.out)
    os.makedirs(OUT_DIR, exist_ok=True)
    target_bytes = int(args.target_mb * 1_000_000)

    written = 0
    n_files = 0
    n_skip = 0
    char_counter: Counter[str] = Counter()
    t0 = time.time()

    print(f"[code] 目标 {args.target_mb:.0f}MB → {out_path}", flush=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        shard_idx = args.start_shard
        downloaded = 0
        while written < target_bytes and downloaded < args.max_shards and shard_idx <= 53:
            fn = f"file-{shard_idx:012d}.json.gz"
            print(f"[code] 下载分片 {fn} （首次约 142MB，HF 缓存可复用）…", flush=True)
            local = hf_hub_download(REPO, fn, repo_type="dataset")
            downloaded += 1
            shard_idx += 1
            for rec in iter_records(local):
                if not keep(rec, args.min_chars, args.max_chars, args.max_line, args.min_alpha):
                    n_skip += 1
                    continue
                content = rec["content"].replace("\r\n", "\n").replace("\r", "\n")
                out.write(content)
                out.write(FILE_SEP)
                char_counter.update(content)
                written += len(content.encode("utf-8")) + len(FILE_SEP)
                n_files += 1
                if n_files % 2000 == 0:
                    print(f"[code]   已写 {written/1e6:6.1f}MB / {n_files} 文件 "
                          f"（跳过 {n_skip}）  {time.time()-t0:.0f}s", flush=True)
                if written >= target_bytes:
                    break

    vocab = len(char_counter)
    # 估算"高频字表"（>=频率门槛的字符数），给训练脚本选词表大小参考
    for thr in (5, 20, 100):
        kept = sum(1 for _, c in char_counter.items() if c >= thr)
        print(f"[code] 字符频率 >= {thr:>3}: {kept} 个不同字符")
    top = "".join(c for c, _ in char_counter.most_common(40))
    print("[code] === 完成 ===", flush=True)
    print(f"[code] 落盘：{out_path}  体积 {written/1e6:.1f}MB  文件数 {n_files}  跳过 {n_skip}")
    print(f"[code] 不同字符总数（含稀有 unicode）：{vocab}")
    print(f"[code] 最常见 40 字符：{top!r}")
    print(f"[code] 用时 {time.time()-t0:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
